export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const START_ACTION = 'START_ACTION';
export const STOP_ACTION = 'STOP_ACTION';
export const REFRESH_ACTION_START = 'REFRESH_ACTION_START';
export const REFRESH_ACTION_STOP = 'REFRESH_ACTION_STOP';

export const NETWORK_ERROR = 'NETWORK_ERROR';
export const NETWORK_INACTIVE = 'NETWORK_INACTIVE';
export const NETWORK_ACTIVE = 'NETWORK_ACTIVE';

export const SHOW_NETWORK_MODAL = 'SHOW_NETWORK_MODAL';
export const HIDE_NETWORK_MODAL = 'HIDE_NETWORK_MODAL';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const FETCH_TOPIC = 'FETCH_TOPIC';
export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_FAILURE = 'FETCH_TOPIC_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const FETCH_PERFORMED_TOPIC = 'FETCH_PERFORMED_TOPIC';
export const FETCH_PERFORMED_TOPIC_SUCCESS = 'FETCH_PERFORMED_TOPIC_SUCCESS';
export const FETCH_PERFORMED_TOPIC_FAILURE = 'FETCH_PERFORMED_TOPIC_FAILURE';

export const SUBMIT_IMAGES = 'SUBMIT_IMAGES';
export const SUBMIT_IMAGES_SUCCESS = 'SUBMIT_IMAGES_SUCCESS';
export const SUBMIT_IMAGES_FAILURE = 'SUBMIT_IMAGES_FAILURE';

export const APPROVE_TASK = 'APPROVE_TASK';
export const APPROVE_TASK_SUCCESS = 'APPROVE_TASK_SUCCESS';
export const APPROVE_TASK_FAILURE = 'APPROVE_TASK_FAILURE';
